DECLARE
V_SAL NUMBER(4);
BEGIN
V_SAL:=500;

CASE V_SAL
    WHEN 200 THEN
        DBMS_OUTPUT.PUT_LINE('VALUE IS : '|| V_SAL);
    WHEN 400 THEN 
        DBMS_OUTPUT.PUT_LINE('VALUE IS : '|| V_SAL);
    ELSE
        DBMS_OUTPUT.PUT_LINE('THIS IS DEFAULT CASE' );
END CASE;

END;